### ISSUE TITLE
got issue about verify_ssl in sms.py

### ISSUE THREAD

**Issue by NovrianSPT12** [un1cum/Beast_Bomber#100]
Hey there, i got problem when i try to start beast.py, when i start it, even a problem arose

TypeError: FakeUserAgent.__init__() got an unexpected keyword argument 'verify_ssl'

Anyone can fix that problem?
![Screenshot_20230802_140808_Termux](https://github.com/un1cum/Beast_Bomber/assets/105198163/99ae991e-0b00-43e6-b67d-e859cabedb85)

**Comment by un1cum** [comment]
The problem is in the pip package `fake-useragent`. Due to the latest update of this package, which made critical changes, the script stopped working. You can install the previous version of this package, then everything will work:

```
pip uninstall fake-useragent && pip install fake-useragent~=1.1.3
```

**P.S if you had followed the** [installation instructions](https://github.com/un1cum/Beast_Bomber/tree/main#-manual) **and installed all dependencies from the** [requirements.txt](https://github.com/un1cum/Beast_Bomber/blob/main/requirements.txt) **file, you would not have gotten this error ;)**

![Screenshot_1](https://github.com/un1cum/Beast_Bomber/assets/80776324/1099b8af-908b-4f2a-8e2f-20977608ae69)
