### ISSUE TITLE
does nothing?

### ISSUE THREAD

**Issue by LinuxRocks2000** [un1cum/Beast_Bomber#101]
I tested with both email and discord spam. No results whatsoever. Looks like they've both been patched?

**Comment by un1cum** [comment]
**Your message is not informative**. Spam may not be sent for various reasons, for example, the spam accounts you are using are not working, services are using an anti-spam system, etc. In any case, please read the [setup instructions](https://github.com/un1cum/Beast_Bomber#-first-setup), probably you missed something and try again. If the problem is in the script itself, the only way out is to wait for an update.
