### ISSUE TITLE
NON_ASCII ERROR ?

### ISSUE THREAD

**Issue by Cyrilnkl** [un1cum/Beast_Bomber#65]
Hey, I still have some errors like this one. Could you help me please ?

<img width="1188" alt="Capture d’écran 2023-02-08 à 12 35 45" src="https://user-images.githubusercontent.com/65498535/217518974-aba877cb-557f-43a4-8d59-557b48a204fc.png">

**Comment by un1cum** [comment]
Try to reinstall **pip and python** and install beast bomber again following the instructions in the repository, it's easy and shouldn't be a problem if you did everything according to the instructions. 

If none of the above helps, the problem is entirely on your end and I have no idea how to fix it, just use google 🤷‍♂️
