### ISSUE TITLE
Stuck 

### ISSUE THREAD

**Issue by myk-coder** [un1cum/Beast_Bomber#66]
Im stuck here

 File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>

![image](https://user-images.githubusercontent.com/103906906/217828868-7f7159d3-12e0-40f0-a3d4-f17fa97b8caa.png)

**Comment by un1cum** [comment]
You have something wrong with the encoding, try reinstalling Python, and run beast bomber in cmd instead of git bash, although it should run fine in git bash too. 

![image](https://user-images.githubusercontent.com/80776324/217836930-9da465ee-479a-462e-8598-b72690e2808f.png)

If that doesn't help, use google, because I have no idea how to solve this error.

**Comment by myk-coder** [comment]
can I use my kali os? or can you suggest a lighter os i can use to test your software before i talk big deals with you

**Comment by myk-coder** [comment]
hello bro, my kali is now up, can you suggest where i get cheaper static proxies from please, fineproxy is not really fine

**Comment by un1cum** [comment]
I buy proxies here:
https://proxy-seller.io
https://proxys.io

**Comment by myk-coder** [comment]
Ok but how to inject in Python code to run the the API on the proxy
