### ISSUE TITLE
having trouble

### ISSUE THREAD

**Issue by franchiseplayer** [un1cum/Beast_Bomber#82]
so i downloaded all the requirements but im still having trouble trying to open the application when i do it just crashes also im on laptop idk if thats a problem.

**Comment by un1cum** [comment]
If the script won't run, try reinstalling it according to the instructions: https://github.com/un1cum/Beast_Bomber#-installation

If after installing the script according to the instructions it still won't run, then the problem is on your side. Try reinstalling Python and pip and then reinstall the script.

Just give a tip for the future, explain your problem as much as possible in detail and preferably with screenshots, so the developer will be easier to understand the problem and help sort it out.

**P.S If for some reason you can't install/run the script, you can always run the online version on replit: https://replit.com/@un1cum/Beast-Bomber or use telegram bot: https://t.me/idfhgsdwaefwe_caramel_bot**

That's all I can help you with.
